apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "feedback-fountain.fullname" . }}-feedback-fountain-api
  labels:
    {{- include "feedback-fountain.labels" . | nindent 4 }}
stringData:
  MS_ACS_API_TOKEN: {{ .Values.api.acs.token | required "A value for .Values.api.acs.token is required" }}
