apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "feedback-fountain.fullname" . }}-feedback-fountain-api
  labels:
    {{- include "feedback-fountain.labels" . | nindent 4 }}
    app.kubernetes.io/component: feedback-fountain-api
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host | required "A value for .Values.ingress.host is required" }}`) && PathPrefix(`/{{ include "feedback-fountain.fullname" . }}-feedback-fountain-api`)
      kind: Rule
      services:
        - name: {{ include "feedback-fountain.fullname" . }}-feedback-fountain-api
          port: 8080
      middlewares:
        - name: {{ include "feedback-fountain.fullname" . }}-feedback-fountain-api-prefix
        - name: {{ include "feedback-fountain.fullname" . }}-feedback-fountain-api-security
        - name: {{ include "feedback-fountain.fullname" . }}-feedback-fountain-api-ratelimit
        - name: {{ include "feedback-fountain.fullname" . }}-feedback-fountain-api-compress
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "feedback-fountain.fullname" . }}-feedback-fountain-api-prefix
  labels:
    {{- include "feedback-fountain.labels" . | nindent 4 }}
    app.kubernetes.io/component: feedback-fountain-api
spec:
  stripPrefix:
    prefixes:
      - "/{{ include "feedback-fountain.fullname" . }}-feedback-fountain-api"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "feedback-fountain.fullname" . }}-feedback-fountain-api-security
  labels:
    {{- include "feedback-fountain.labels" . | nindent 4 }}
    app.kubernetes.io/component: feedback-fountain-api
spec:
  headers:
    browserXssFilter: true
    frameDeny: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "feedback-fountain.fullname" . }}-feedback-fountain-api-ratelimit
  labels:
    {{- include "feedback-fountain.labels" . | nindent 4 }}
    app.kubernetes.io/component: feedback-fountain-api
spec:
  rateLimit:
    average: 1
    burst: 5
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "feedback-fountain.fullname" . }}-feedback-fountain-api-compress
  labels:
    {{- include "feedback-fountain.labels" . | nindent 4 }}
    app.kubernetes.io/component: feedback-fountain-api
spec:
  compress: {}
