apiVersion: v1
kind: Service
metadata:
  name: {{ include "feedback-fountain.fullname" . }}-feedback-fountain-api
  labels:
    {{- include "feedback-fountain.labels" . | nindent 4 }}
    app.kubernetes.io/component: feedback-fountain-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "feedback-fountain.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: feedback-fountain-api
